# https://canonical-charm-refresh.readthedocs-hosted.com/latest/refresh-versions-toml/

charm = "v8/1.10.0"
charm_major = 1
workload = "8.0.10"

[snap]
name = "charmed-mongodb"

[snap.revisions]
# amd64
x86_64 = "133"
