[tool.poetry]
package-mode = false
requires-poetry = ">=2.0.0"

[tool.poetry.dependencies]
python = "^3.12.3"
mongo-charms-single-kernel = "*"
rpds-py = "0.18.0"
ops = "*"
pydantic = "*"  # cos_agent lib
cryptography = "*"  # tls_certificates lib v3
jsonschema = "*"  # tls_certificates lib v3
cosl = "*"  # loki_push_api


[tool.poetry.group.build-refresh-version]
optional = true

[tool.poetry.group.build-refresh-version.dependencies]
charm-refresh-build-version = "^0.4.0"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[build-system]
build-backend = "poetry.core.masonry.api"
