[project]
name="mongodb-workflow-cli"
version = "0.0.1"
description = ""
authors = [
    {name = "Neha Oudin", email = "neha.oudin@canonical.com"}
]
readme = "README.md"
dependencies = []

[project.scripts]
compute-tag = "src.compute_tag:main"
create-tag = "src.create_tag:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I", "UP"]
