name: Bump dependent charm versions

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  update-dependent-charms:
    name: Open PRs in dependent charm repos
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - canonical/mongodb-operator
          - canonical/mongodb-k8s-operator
          - canonical/mongos-k8s-operator
          - canonical/mongos-operator

    permissions:
      contents: write
      pull-requests: write

    env:
      VERSION: ${{ inputs.version }}
      BASE_BRANCH: ${{ inputs.branch_name }}
      DEP_NAME: mongo-charms-single-kernel

    steps:
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@v31.1.1#subdirectory=python/cli
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.PAT }}
          ref: ${{ env.BASE_BRANCH }}

      - name: Install poetry
        run: pipx install poetry
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y  build-essential python3-dev libldap-dev libsasl2-dev

      - name: Create update branch
        run: |
          BRANCH="bump-${DEP_NAME}-${VERSION}"
          git checkout -b "$BRANCH"

      - name: Update dependency version in pyproject.toml
        run: |
          poetry remove "${DEP_NAME}"
          poetry add "${DEP_NAME}"=="${VERSION}" --group main
          poetry add "${DEP_NAME}"=="${VERSION}" --group integration

      - name: Poetry update
        run: poetry update "${DEP_NAME}"

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml poetry.lock
          git commit -m "Bump ${DEP_NAME} to version ${VERSION}"

      - name: Push branch
        run: |
          git push origin "$BRANCH" -f

      - name: Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr create \
            --title "Bump ${DEP_NAME} to ${VERSION}" \
            --body "Automated bump of \`${DEP_NAME}\` to version \`${VERSION}\` after PyPI release." \
            --base ${{ env.BASE_BRANCH }}  \
            --head "$BRANCH"
