name: Run integration tests

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - "docs/**"
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      GCP_ACCESS_KEY:
        required: true
      GCP_SECRET_KEY:
        required: true
      GCS_SERVICE_ACCOUNT:
        required: true

jobs:
  build:
    strategy:
      matrix:
        path:
          - tests/charms/mongodb_test_charm
          - tests/charms/mongodb_k8s_test_charm
          - tests/charms/mongos_test_charm
          - tests/charms/mongos_k8s_test_charm
    name: Build Test charm | ${{ matrix.path }}
    uses: ./.github/workflows/build_test_charms.yaml
    with:
      path-to-charm-directory: ${{ matrix.path }}
      artifact-prefix: packed-charm
      cache: true
    permissions:
      contents: read

  build-helpers:
    strategy:
      matrix:
        path:
          - tests/integration/applications/client_relations_charm
          - tests/integration/applications/continuous_write_charm
          - tests/integration/applications/mongos_client_charm
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v50.2.1
    with:
      path-to-charm-directory: ${{ matrix.path }}
      artifact-prefix: packed-charm
      cache: true
    permissions:
      contents: read

  integration-test:
    name: Integration test charm
    needs:
      - build
      - build-helpers
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      GCP_ACCESS_KEY: ${{ secrets.GCP_ACCESS_KEY }}
      GCP_SECRET_KEY: ${{ secrets.GCP_SECRET_KEY }}
      GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}
    permissions:
      contents: write # Needed for Allure Report
