name: Run tests

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        path:
          - tests/charms/mongodb_test_charm
          - tests/charms/mongodb_k8s_test_charm
          - tests/charms/mongos_test_charm
          - tests/charms/mongos_k8s_test_charm
          - tests/integration/applications/client_relations_charm
          - tests/integration/applications/continuous_write_charm
          - tests/integration/applications/mongos_client_charm
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v35.0.4
    with:
      path-to-charm-directory: ${{ matrix.path }}

  integration-test:
    name: Integration test charm
    needs:
      - build
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: packed-charm
    secrets: inherit
    permissions:
      contents: write  # Needed for Allure Report
