name: Trigger integration tests

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute.outputs.matrix }}
      authorized: ${{ steps.auth_check.outputs.authorized }}
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    timeout-minutes: 5
    steps:
      - name: Check commenter
        id: auth_check
        uses: morfien101/actions-authorized-user@4a3cfbf0bcb3cafe4a71710a278920c5d94bb38b
        with:
          username: ${{ github.event.comment.author.login }}
          org: "Canonical"
          team: "data-ai-engineers"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Compute matrix
        id: compute
        shell: bash
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          matrix=$(python3 scripts/split_matrix.py)
          if [ "$matrix" = "[]" ]; then
            echo "::error Invalid matcher '$COMMENT'"
            exit 1
          fi
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"

  publish_dev:
    needs: ["compute-matrix"]
    if: ${{ needs.compute-matrix.outputs.authorized }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      new_version: ${{ steps.compute_version.outputs.new_version }}
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@e8b8daa837e8ea7331c0003c9c316a64c6d8b0b1
        id: comment-branch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ steps.comment-branch.outputs.head_sha }}"
          persist-credentials: false
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Get current version
        run: echo "CURRENT_VERSION=$(poetry version --short)" >> "$GITHUB_ENV"
      - name: Compute new version
        id: compute_version
        shell: bash
        run: |
          SHORT_SHA=$(echo ${{ steps.comment-branch.outputs.head_sha }} | head -c 8)
          echo "new_version=${{ env.CURRENT_VERSION }}-dev$((0x$SHORT_SHA))" >> "$GITHUB_OUTPUT"
      - name: Set new version
        shell: bash
        run: |
          poetry version ${{ steps.compute_version.outputs.new_version }}
      - name: Build dev version
        shell: bash
        run: |
          poetry build
      - name: Publish to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
    permissions:
      id-token: write  # Needed for trusted publishing (https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)

  trigger:
    needs: ["compute-matrix", "publish_dev"]
    if: ${{ needs.compute-matrix.outputs.authorized }}
    strategy:
      matrix:
        repository: ${{ fromJson(needs.compute-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@e8b8daa837e8ea7331c0003c9c316a64c6d8b0b1
        id: comment-branch
      - name: Update python library and create PR on ${{ matrix.repository }}
        id: remoteupdater
        uses: Gu1nness/poetry-remote-update@main
        with:
          library: 'mongo-charms-single-kernel'
          new_version: '${{ needs.publish_dev.outputs.new_version }}'
          groups: '["main", "integration", "unit"]'
          repository: 'Canonical/${{ matrix.repository }}'
          branch: '6/edge'
          new_branch: '${{ steps.comment-branch.outputs.head_ref }}'
          python_version: '3.10'
          pat: '${{ secrets.PAT }}'
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
        with:
          message: |
            * ${{ steps.remoteupdater.outputs.pull-request-operation }} [${{ matrix.repository }} PR](${{ steps.remoteupdater.outputs.pull-request-url }})
          pr-number: ${{ github.event.issue.id }}
