on:
  # GitHub will only trigger workflows `on: schedule` for workflow files in the default GitHub branch
  schedule:
    - cron: "0 2 * * 6" # Every Saturday 2:00 AM UTC

jobs:
  trigger:
    name: Trigger workflow on branch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Trigger workflow
        run: gh workflow --repo '${{ github.repository }}' run tics_run.yaml --ref 6/edge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      actions: write  # Needed to trigger workflow
